version: "3.9"

services:
  signals-workshop:
    # image: utkusarioglu/conda-music-devcontainer:1.0.15
    image: utkusarioglu/conda-music-devcontainer:experiment-feat-music-sequencer-8
    # image: utkusarioglu/conda-music-devcontainer:experiment-feature-pip-7
    # image: utkusarioglu/conda-music-devcontainer:experiment-feature-pip-33
    extra_hosts:
      supercollider: host-gateway
      touch_osc: host-gateway
    ports:
      - 5000:5000
    # devices:
    #   - $PULSE_SERVER:/dev/snd
    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/signals-workshop/src
      PULSE_SERVER: ${PULSE_SERVER}
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/signals-workshop
      - type: bind
        source: /mnt/wslg
        target: /mnt/wslg
