version: "3.9"

services:
  signals-workshop:
    image: utkusarioglu/conda-music-devcontainer:1.0.11

    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/signals
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/signals
