services:
  signals-workshop:
    image: utkusarioglu/conda-music-devcontainer:3.13-ubuntu-test-24
    extra_hosts:
      # supercollider: host-gateway
      supercollider: 192.168.1.151
    ports:
      - 5000:5000
      - 5005:5005/udp
    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/signals-workshop/src
      PULSE_SERVER: unix:/mnt/wslg/PulseServer

      ARTIFACTS_ABSPATH: /utkusarioglu-com/workshops/signals-workshop/artifacts
      ASSETS_ABSPATH: /assets

    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/signals-workshop

      - type: bind
        source: /mnt/wslg/PulseServer
        target: /mnt/wslg/PulseServer
      
      - type: bind
        source: /mnt/d/Audio
        target: /assets
